### ISSUE TITLE
cropping does not do anything at all

### ISSUE THREAD

**Issue by bertsky** [mjenckel/ocrd_anybaseocr#11]
In e1ca17b9, the complete functionality of `ocrd-anybaseocr-crop` has been commented out. All it does now is print the `@imageFilename`. What's going on?

**Comment by mjenckel** [comment]
Thank you for the notice!
We just checked and noticed that in the recent past some commits that were meant for the development branch ended up on the master branch.
We will see how far we have to roll back or if we can quickly resolve this with an update and let you know. We are sorry for the inconvenience.
