### ISSUE TITLE
ocrd-anybaseocr-textline: create inverted images

### ISSUE THREAD

**Issue by VolkerHartmann** [mjenckel/ocrd_anybaseocr#26]
The following workflow produces inverted images of lines:
ocrd-anybaseocr-binarize
ocrd-anybaseocr-deskew
ocrd-anybaseocr-crop
ocrd-anybaseocr-tiseg
ocrd-anybaseocr-textline

**Comment by khurramHashmi** [comment]
This issue is resolved.

**Comment by kba** [comment]
> This issue is resolved.

How? Where?

**Comment by khurramHashmi** [comment]
https://github.com/mjenckel/ocrd_anybaseocr/pull/27/commits/0ac8567b1faffdd8bc5e1c67a74fb03761404661

**Comment by kba** [comment]
Is https://github.com/mjenckel/ocrd_anybaseocr/compare/region_cropping_problem the current development branch? Why is it not up-to-date with master?

> This branch is 28 commits ahead, 10 commits behind master.
