### ISSUE TITLE
Where are the "parameter files"?

### ISSUE THREAD

**Issue by wrznr** [mjenckel/ocrd_anybaseocr#33]
A number of the processors provided by the DFKI requires parameter files. Where can I get those?

**Comment by mahmed1995** [comment]
What exactly do you mean by parameters file? Do you mean the trained model files?

**Comment by wrznr** [comment]
@mahmed1995 How am I supposed to know? It is your documentation I am referring to (https://github.com/mjenckel/ocrd_anybaseocr/blob/master/README.md#usage-7). At some other point  it is called `block_segmentation_model` or `block_segmentation_weights` (https://github.com/mjenckel/ocrd_anybaseocr/blob/fa01ea3d93e31a77fc5aa2604431ecc4b2504067/ocrd_anybaseocr/cli/ocrd_anybaseocr_block_segmentation.py#L80). It is all very confusing. Let me phrase it this way: I want to test your OCR-D processors but it is just not possible due to multiple issues. Please help.

**Comment by mahmed1995** [comment]
@wrznr I updated the Readme.md in ocrd_anybaseocr/models folder. You can download all the trained models by the links provided in Readme.md
Commit: 1c1f6e9

**Comment by wrznr** [comment]
Many thanks @mahmed1995 !
