### ISSUE TITLE
parameter "force" does not work

### ISSUE THREAD

**Issue by stefanCCS** [mjenckel/ocrd_anybaseocr#43]
Hi,
when using the paramter "force" (this way:
"force":true 
)
I would expect this existing data in METS will be overwritten.
But I get an error like this
" Output fileGrp[@USE='OCR-D-DEWARP'] already in METS!"
Could you please check this?

**Comment by kba** [comment]
Workaround:

```
ocrd workspace remove-group -f OCR-D-DEWARP
```

**Comment by stefanCCS** [comment]
> 
> 
> Workaround:
> 
> ```
> ocrd workspace remove-group -f OCR-D-DEWARP
> ```

Together with -r (recursiv) this workaround works fine.
Many thanks.
