### ISSUE TITLE
ocrd-anybaseocr-block-segmentation handles multiple output groups not correct

### ISSUE THREAD

**Issue by VolkerHartmann** [mjenckel/ocrd_anybaseocr#44]
similar to the bug in https://github.com/mjenckel/ocrd_anybaseocr/issues/39

**Comment by khurramHashmi** [comment]
Resolved in Commit : 42973ed

**Comment by kba** [comment]
Multiple output file groups no longer supported since [1.0.0](https://github.com/OCR-D/ocrd_anybaseocr/releases/v1.0.0)
