### ISSUE TITLE
tiseg will not work with default model

### ISSUE THREAD

**Issue by VolkerHartmann** [mjenckel/ocrd_anybaseocr#45]
I used this model: https://cloud.dfki.de/owncloud/index.php/s/Qxm8baqq9Zf8brQ/download and got the following error: 
ValueError: You are trying to load a weight file containing 99 layers into a model with 95 layers.

**Comment by mahmed1995** [comment]
I ran the code again, its working without any errors on my side. Could you kindly check if you have latest code?

**Comment by VolkerHartmann** [comment]
You are right. I used the version from Feb 18.
Now it works with one warning:
UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
