### ISSUE TITLE
Duplicate heading in README files

### ISSUE THREAD

**Issue by wrznr** [mjenckel/ocrd_anybaseocr#5]
Both tool-specific README files have the same heading although they are referring to different processing steps. Maybe a single README.md file would be more useful for the users?

**Comment by n00blet** [comment]
README files have been updated in this commit 9a32b721c0b589d261452f4bc19a517729810efd.
For now, we have separate README for each of the processing steps, later we will have a single README for the entire LAYoutERkennung repo.
