### ISSUE TITLE
Make pytorch code device-agnostic

### ISSUE THREAD

**Issue by sepastian** [mjenckel/ocrd_anybaseocr#52]
As recommended in the [pytorch best practices](https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code).

(I'm opening this issue by request from @bertsky, see https://github.com/OCR-D/core/pull/452.)

**Comment by bertsky** [comment]
@kba can you make that change please? It's a one-liner that will remove the only GPU-only processor requirement in all of OCR-D.
