### ISSUE TITLE
ocrd-anybaseocr-crop: Illegal instruction

### ISSUE THREAD

**Issue by M3ssman** [mjenckel/ocrd_anybaseocr#55]
Hello,
actually, on a plain Ubuntu 18.04 LTS Server VM the run od `ocrd-anybaseocr-crop` via `ocrd/all:maximum` fails with (last output lines, for full output see [1000.ulb-ocrd-vd18-01.log](https://github.com/OCR-D/ocrd_anybaseocr/files/4538352/1000.ulb-ocrd-vd18-01.log)
) 

```
08:15:43.587 INFO ocrd-olena-binarize - processing image/png input file IMG_OCR-D-IMG-PNG_1246738 ()
Warning: integral_browsing - Adjusting window width since it was larger than image height.
Warning: integral_browsing - Adjusting window height since it was larger than image width.
Warning: integral_browsing - Adjusting window width since it was larger than image height.
Warning: integral_browsing - Adjusting window width since it was larger than image height.
Warning: integral_browsing - Adjusting window height since it was larger than image width.
Warning: integral_browsing - Adjusting window width since it was larger than image height.
Warning: integral_browsing - Adjusting window width since it was larger than image height.
Warning: integral_browsing - Adjusting window height since it was larger than image width.
Warning: integral_browsing - Adjusting window width since it was larger than image height.
2020-04-27 08:15:45,221.221 INFO ocrd.workspace - Saving mets '/data/1000/mets.xml'
2020-04-27 08:15:46,668.668 INFO ocrd.workspace - Saving mets '/data/1000/mets.xml'
building OCR-D-SEG-PAGE-anyocr from OCR-D-BINPAGE-sauvola with pattern rule for ocrd-anybaseocr-crop
ocrd workspace remove-group -r OCR-D-SEG-PAGE-anyocr 2>/dev/null || true
ocrd-anybaseocr-crop -I OCR-D-BINPAGE-sauvola -O OCR-D-SEG-PAGE-anyocr -p OCR-D-SEG-PAGE-anyocr.json 2>&1 | tee OCR-D-SEG-PAGE-anyocr.log && touch -c OCR-D-SEG-PAGE-anyocr || { rm -fr OCR-D-SEG-PAGE-anyocr.json OCR-D-SEG-PAGE-anyocr; exit 1; }
2020-04-27 08:15:49,086.086 INFO matplotlib.font_manager - generated new fontManager
bash: line 1:  2230 Illegal instruction     (core dumped) ocrd-anybaseocr-crop -I OCR-D-BINPAGE-sauvola -O OCR-D-SEG-PAGE-anyocr -p OCR-D-SEG-PAGE-anyocr.json 2>&1
      2231 Done                    | tee OCR-D-SEG-PAGE-anyocr.log
Makefile:304: recipe for target 'OCR-D-SEG-PAGE-anyocr' failed
make[1]: *** [OCR-D-SEG-PAGE-anyocr] Error 1
make[1]: Leaving directory '/data/1000'
```

Anybody got an idea what's wrong?

**Comment by M3ssman** [comment]
Something strage about `ocrd-anybaseocr-crop` ...

When I run plain `ocrd-anybaseocr-crop --version` inside the container (from image  `ocrd/all               maximum             566cf5a2916a        4 days ago          6.13GB`) in the System-in-Question (SIQ) I get:

```
Using TensorFlow backend.
Illegal instruction (core dumped)

```

On my local Ubuntu 18.04 LTS machine, also inside container (image `ocrd/all              maximum             566cf5a2916a        4 days ago          6.13GB`):

```
root@5250f035613b:/data# ocrd-anybaseocr-crop --version
2020-04-27 09:05:32,594.594 INFO matplotlib.font_manager - generated new fontManager
Using TensorFlow backend.
2020-04-27 09:05:34,714.714 WARNING tensorflow - From /usr/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Version 0.0.1, ocrd/core 2.5.0
```
I've played around on my local system with tensorflow and keras, but this shouldn't affect the Container.

**Comment by bertsky** [comment]
Indeed, this coupling of `crop` ~~and `tiseg`~~, which ~~are~~ is only rule-based, with components requiring Pytorch and Tensorflow in a single repo is unfortunate.

> Using TensorFlow backend.
> Illegal instruction (core dumped)

Check your Tensorflow distribution. Often the prebuilt images require certain CPU extensions (like [AVX since TF 1.6](https://github.com/tensorflow/tensorflow/issues/18689)). You may have to [build](https://www.tensorflow.org/install/source) yourself and install that wheel over the prebuilt package. (But be warned: TF build takes a lot of CPU time and is often quirky.)

> I've played around on my local system with tensorflow and keras, but this shouldn't affect the Container.

Indeed, you'll have to build TF _inside_ the container, and then amend the image permanently with your new version.

**Comment by M3ssman** [comment]
@bertsky In both contexts I do run Makefile-OCR-D-Worksflows in containers created from `ocrd/all:maximum` image. The base-Images are identic (see above), and inside the `ocrd/all` Docker images are dependencies IMO should be fetched already. Therefore my confusion. Do you mean I should check the Docker-Hosts for CPU-Extensions? Are those used inside the containers? Do we need VMs for the Docker containers of `ocrd/all:maximum` with GPU enabled or stuff like that?

**Comment by bertsky** [comment]
> and inside the `ocrd/all` Docker images are dependencies IMO should be fetched already.

They are. Only not **for _your_ CPU**.

> Do you mean I should check the Docker-Hosts for CPU-Extensions?

Exactly.

For example:

    LC_ALL=C lscpu | grep ^Flags | fgrep -w avx


> Are those used inside the containers?

Each binary package comes with its own assumptions. Ubuntu packages themselves do AFAIK not depend on AVX. (But there have been a number of deliberate backwards CPU incompatibilities over the years.)

Python wheels are usually built for a number of architectures. But TF is quite intolerant.

> Do we need VMs for the Docker containers of `ocrd/all:maximum` with GPU enabled or stuff like that?

Not really. OCR-D module projects were required to use GPUs as _opt-in_. DFKI's dewarping is a known counter-example, but should not be hard to [fix](https://github.com/OCR-D/ocrd_anybaseocr/issues/52). And yes, obviously this has repercussions for our Docker deployment – at the moment this processor [cannot be run](https://github.com/OCR-D/ocrd_anybaseocr/issues/50) with Docker even if the host system does have a GPU.

**Comment by M3ssman** [comment]
@bertsky Thank you very much! I picked the easy way and switched to another OCR-Host of our cluster that has `avx` enabled and it's running fine!
