### ISSUE TITLE
The links to the models are not working

### ISSUE THREAD

**Issue by argonavist** [mjenckel/ocrd_anybaseocr#76]
Models links: https://github.com/OCR-D/ocrd_anybaseocr/tree/master/ocrd_anybaseocr/models

![model_links](https://user-images.githubusercontent.com/16656731/99184521-1e0b8000-274c-11eb-9de3-c0b03e9204d2.png)

**Comment by kba** [comment]
Yes, it looks like DFKI purged the OCR-D models from their owncloud.

For now, the models are available from KIT Karlsruhe at https://ocr-d-repo.scc.kit.edu/models/dfki/ I'll adapt the README accordingly.
