### ISSUE TITLE
Name clash of module directory

### ISSUE THREAD

**Issue by kba** [mjenckel/ocrd_anybaseocr#8]
Since both https://github.com/syedsaqibbukhari/docanalysis and this repo have their source code in a folder `ocrd_anybaseocr`, one cannot install both. Please choose a different name or merge the repos.

**Comment by n00blet** [comment]
@kba yes, realized the error in naming conventions. I will have a discussion with @mjenckel about wanting to merge the repos or choosing a different name for source folder and update you by tomorrow.

**Comment by n00blet** [comment]
This issue has been resolved now in 6ca4ededd8506abfb9ff64647a97f6edd111f582, as all the pre-processing scripts from the previous repo https://github.com/syedsaqibbukhari/docanalysis has been moved here.
