### ISSUE TITLE
cropper screws up royally

### ISSUE THREAD

**Issue by bertsky** [mjenckel/ocrd_anybaseocr#83]
Under certain conditions, `ocrd-anybaseocr-crop` selects **only noise** fragments of a page. It seems to be related to its builtin ad-hoc textline detection filter which is based on a number of assumptions (e.g. fixed kernel sizes indicate a certain pixel resolution and/or font size is expected).

Here's an example:
- raw image: 
  <img src="https://user-images.githubusercontent.com/38561704/112199526-8abcec80-8c0e-11eb-8d45-54b6d0555e31.jpg" width="500" alt="kalo_anon"/>
- binarized (`sauvola-ms-split`) image: 
  <img src="https://user-images.githubusercontent.com/38561704/112199598-9dcfbc80-8c0e-11eb-8930-afbd1d9b720d.png" width="500" alt="OCR-D-BIN_kalo_anon-BIN_sauvola-ms-split"/>
- cropped image: 
  <img src="https://user-images.githubusercontent.com/38561704/112210411-f2793480-8c1a-11eb-9377-b9613498d579.png" width="50" alt="OCR-D-CROP_kalo_anon-IMG"/>

Looking at the debug images being created along the process (after repairing the array conversion dynamic range), it seems that the only criterion for text areas is a morphological closing with a fixed kernel size, which captures the texture of the background around the page:
![OCR-D-CROP_kalo_anon-IMG debug textarea_closed](https://user-images.githubusercontent.com/38561704/112233458-c7064200-8c3a-11eb-8e01-51c044a4e28c.png)

(I wonder why no better method of textline detection was used...)

Then, in turn, the text boxes/columns of course look bad:
![OCR-D-CROP_kalo_anon-IMG debug textarea_boxes](https://user-images.githubusercontent.com/38561704/112233534-ea30f180-8c3a-11eb-9022-af011d735696.png)

In the end, the default `minArea` parameter of 0.05 removes all but the largest "column":
![OCR-D-CROP_kalo_anon-IMG debug textarea_boxes_areafiltered](https://user-images.githubusercontent.com/38561704/112233667-1f3d4400-8c3b-11eb-97b0-71fcdf1e92e7.png)

This sheds a very bad light on that part of the algorithm. 

But there's also the fallback mechanism of [pylsd](http://www.ipol.im/pub/art/2012/gjmr-lsd/) edge detection based border rectangle estimation. Since it is based on subpixel edge detection, this only works at all when _running on the raw RGB image_ (instead of binarized), though. However, this works perfectly well:

First, the morphological closure again, this time of the raw image: 
![OCR-D-CROP-RAW_kalo_anon-IMG debug_textarea_closed](https://user-images.githubusercontent.com/38561704/112237290-aa6e0800-8c42-11eb-9001-4a7082d0009c.png)

This will find us _no_ large enough text components to work with! 

Now the edge detection comes into play: 
![OCR-D-CROP-RAW_kalo_anon-IMG debug_lsd_edges](https://user-images.githubusercontent.com/38561704/112237346-c83b6d00-8c42-11eb-91d0-aa8a0d29f7d9.png)

And from that its comparably easy to plausibilize the largest intersecting horizontal and vertical lines: 
![OCR-D-CROP-RAW_kalo_anon-IMG debug_border_rect](https://user-images.githubusercontent.com/38561704/112237406-e6a16880-8c42-11eb-86ab-c2cd702cb522.png)

Final cropped raw image: 
<img src="https://user-images.githubusercontent.com/38561704/112237450-fcaf2900-8c42-11eb-9381-97c4cf61cba0.png" width="500" alt="OCR-D-CROP-RAW_kalo_anon-IMG"/>

**Comment by kba** [comment]
Thanks for investigating. Does this mean that the cropper should only be used on RGB images so the pylsd edge detection is executed?

**Comment by bertsky** [comment]
> Does this mean that the cropper should only be used on RGB images so the pylsd edge detection is executed?

Yes, but in the current implementation with `feature_selector=binarized` you'd have to fake the binarization in the input. So really the code (including the OCR-D part) needs to be changed to take the raw image (for the pylsd part). However, for the textarea detector part, currently it uses an ad-hoc Otsu, which is clearly not a good choice. So at that point, one would need to take the binarized image from OCR-D (and probably modify the kernel size based on input image DPI with the usual zoom heuristic).
