### ISSUE TITLE
dewarping: `gpu_id` does not default to `-1` in any case

### ISSUE THREAD

**Issue by mweidling** [mjenckel/ocrd_anybaseocr#87]
Using `ocrd/all:maximum` I get the following error when executing `ocrd-anybaseocr-dewarp -I OCR-D-DESKEW-PAGE -O OCR-D-DEWARP-PAGE`:

> RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

On the other hand, explicitly passing `-gpu_id=-1` yields

> model [Pix2PixHDModel] was created

I would have expected from the docs that `-gpu_id=-1` is the default and implicitly passed, while what I see implies the contrary.

**Comment by mweidling** [comment]
I just noticed that there is no further output apart from the message `model [Pix2PixHDModel] was created` (i.e. no dir OCR-D-DEWARP-PAGE has been created), so there seems to be another problem that doesn't throw an error.

**Comment by bertsky** [comment]
Yes, CPU fallback is [broken](https://github.com/OCR-D/ocrd_anybaseocr/issues/61#issuecomment-647048214), but so is the whole processor (see #72 and #42). 

IIRC we long ago decided to abandon the whole module – except for the cropper (for which I still have an improved version in the pipeline, and wanted to factor that out into ocrd_cis later-on).

**Comment by mweidling** [comment]
Ah, okay, thanks for the explanation! I was simply confused by the docs on the website which doesn't indicate that this is broken.

**Comment by kba** [comment]
fixed by #89
